Peonies/Models/Client.cs
using System.Data.Entity;

namespace Peonies.Models
{
    public class Client
    {
        public int ClientId { get; set; }
        public string Name { get; set; }
        public virtual List <Order> Orders { get; set; }
    }
}

Peonies/Models/ErrorViewModel.cs
namespace Peonies.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Peonies/Models/Order.cs
using System.Data.Entity;

namespace Peonies.Models
{
    public class Order
    {
        public int OrderID { get; set; }
        public string Number { get; set; }
        public DateTime CreatedOn { get; set; }
        public int Quantity { get; set; }
        public int FullPrice { get; set; }
        public virtual List<Peony> Peonies { get; set; }
        public virtual Client Client { get; set; }
    }
}

Peonies/Models/Peony.cs
using MessagePack;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Reflection.Metadata;

namespace Peonies.Models
{
    public class Peony
    {
        public int PeonyId { get; set; }
        public string Name { get; set; }
        public virtual PeonyType Type { get; set; }
        public virtual Variety Variety { get; set; }
        public int Price { get; set; }
    }
}

Peonies/Models/PeonyType.cs
using System.Data.Entity;

namespace Peonies.Models
{
    public class PeonyType
    {
        public int PeonyTypeId { get; set; }
        public string Name { get; set; }
    }
}

Peonies/Models/Variety.cs
namespace Peonies.Models
{
    public class Variety
    {
        public int VarietyId { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public int Height { get; set; }
        public int Diameter { get; set; }
    }
}

Peonies/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Peonies.DataBaseAccess;
using Peonies.Models;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace Peonies.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class ClientController : Controller
    {

        private MyDbContext dbContext = new MyDbContext();

        // GET: /Clients/
        public IEnumerable<Client> Index(int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            var res = dbContext.Clients
                .OrderBy(x => x.Name)
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .ToList();
            return res;
        }

        // GET: //
        public Client Detail(int id)
        {
            var data = dbContext.Clients
                .Where(x => x.ClientId == id)
                .FirstOrDefault();

            return data;
        }

        [HttpPost]
        public void Add(string name)
        {
            Client client = new Client { Name = name };
            dbContext.Clients.Add(client);
            dbContext.SaveChanges();
        }


        [HttpPut]
        public void Edit(string name, int clientId)
        {
            var client = dbContext.Clients.First(a => a.ClientId == clientId);
            client.Name = name;
            dbContext.SaveChanges();
        }

        [HttpPost]
        public void Delete(int clientId)
        {
            Client client = dbContext.Clients.Find(clientId);
            dbContext.Clients.Remove(client);
            dbContext.SaveChanges();
        }


        [HttpGet]
        public void AddOrder(int id)
        {
            Client client = dbContext.Clients.Find(id);

            var ord = new Order()
            {
                CreatedOn = DateTime.Now,
                Number = "test",
                Client = client
                
            };

            dbContext.Orders.Add(ord);
            dbContext.SaveChanges();
        }
    }
}

Peonies/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using System.Web;

namespace Peonies.Controllers
{
    public class HelloWorldController : Controller
    {
        // 
        // GET: /HelloWorld/ 

        public ActionResult Index()
        { 
            return View();
        }

        // 
        // GET: /HelloWorld/Welcome/ 

        public string Welcome(string name, int ID = 1)
        {
            return HttpUtility.HtmlEncode("Hello " + name + ", ID: " + ID);
        }
    }
}

Peonies/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Peonies.Models;
using System.Diagnostics;

namespace Peonies.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult GetEditClient(int id)
        {
            ViewBag.ClientId = id;  
            return View();
        }

        public IActionResult GetDeleteClient(string name, int id)
        {
            ViewBag.ClientId = id;
            ViewBag.name = name;
            return View();
        }
        public IActionResult GetAddClient()
        {
            return View();
        }

        public IActionResult GetCreateOrder(int id)
        {
            ViewBag.ClientId = id;
            return View();
        }
    }
}

Peonies/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Peonies.DataBaseAccess;
using Peonies.Models;

namespace Peonies.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class OrderController : Controller
    {
        private MyDbContext dbContext = new MyDbContext();

        [HttpPost]
        public void Add(int amount, int fullPrice, int peonyId, int clientId)
        {
            Order order = new Order
            {
                CreatedOn = DateTime.Now,
                Quantity = amount,
                FullPrice = fullPrice,
                Peonies = new List<Peony> {dbContext.Peonies.First(a => a.PeonyId == peonyId) },
                Client = dbContext.Clients.First(a => a.ClientId == clientId)

            };


            dbContext.Orders.Add(order);
            dbContext.SaveChanges();
        }
    }
}

Peonies/Controllers/PeonyController.cs
using Microsoft.AspNetCore.Mvc;
using Peonies.DataBaseAccess;
using Peonies.Models;

namespace Peonies.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class PeonyController
    {
        private MyDbContext dbContext = new MyDbContext();

        // GET: /Peonies/
        public IEnumerable<Peony> Index()
        {
            var res = dbContext.Peonies.ToList();
            return res;
        }


        public Peony Detail(int id)
        {
            var data = dbContext.Peonies.Where(x => x.PeonyId == id).FirstOrDefault();
            return data;
        }
    }
}

Peonies/Views/Client/Detail.cshtml
@model Peonies.Models.Client

@{
    ViewBag.Title = "Detail";
}

<div>Detail</div>

<div>
    <div>Employee</div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Orders.ToList())
        </dd>
    </dl>
</div>
<p>
</p>    

Peonies/Views/Client/Index.cshtml
@model IEnumerable<Peonies.Models.Client>


@{
    ViewBag.Title = "Cleents";
}

<h2>Clients</h2>




<table>
@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ClientId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
    </tr>
}
</table>

<div>
    <hr />
    <dl class="dl-horizontal">
        
    </dl>
</div>


<table>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
           
        </tr>
    }
</table>

<br />

Peonies/Views/HelloWorld/Index.cshtml
@{
    ViewData["Title"] = "Hello World!";
}

Peonies/Views/Home/GetAddClient.cshtml
@{
    ViewData["Title"] = "Add client";
}

<add-client-directive>
</add-client-directive>

Peonies/Views/Home/GetCreateOrder.cshtml
@{
    ViewData["Title"] = "Create order";
}

<create-order-directive client-id=@ViewBag.ClientId>
</create-order-directive>

Peonies/Views/Home/GetDeleteClient.cshtml
@{
    ViewData["Title"] = "Delete";
}


<delete-client-directive client-id=@ViewBag.ClientId name=@ViewBag.name>

</delete-client-directive>

Peonies/Views/Home/GetEditClient.cshtml
@{
    ViewData["Title"] = "Edit";
}

<edit-client-directive client-id=@ViewBag.ClientId>
    
</edit-client-directive>

<h1>edit client @ViewBag.ClientId</h1>

Peonies/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<grid-directive>
</grid-directive>

Peonies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Peonies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Peonies.styles.css" asp-append-version="true" />

   

  @*   <script src="lib/angular/angular-route.js"></script>
    <script type="text/javascript" src="angular.min.js"></script> *@
</head>
<body ng-app="phonecatApp">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js">
    </script>
    <header ng-controller="MyController">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Peonies</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("Hello World", "Index", "HelloWorld", null, new { @class = "navbar-brand" })
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Client</a>
                        </li>
                    </ul>
                </div>
            </div>

            
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Peonies - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/phone-list.component.js" asp-append-version="true"></script>
    <script src="~/js/gridDirective/gridDirective.js" asp-append-version="true"></script>
    <script src="~/js/addclientdirective/addclientdirective.js"></script>
    <script src="~/js/editclientdirective/editclientdirective.js"></script>
    <script src="~/js/deleteclientdirective/deleteclientdirective.js"></script>
    <script src="~/js/createorderdirective/createorderdirective.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>